#ifndef LIBPAIRASSEMBLY_H
#define LIBPAIRASSEMBLY_H

/* Generated with cbindgen:0.29.2 */

/* This file is generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status code returned by C ABI functions.
 */
typedef enum PairasmStatus {
  Ok = 0,
  NoOverlap = 1,
  InvalidInput = 2,
  AssemblyError = 3,
  Panic = 255,
} PairasmStatus;

/**
 * Opaque assembler handle owned by Rust and passed through C as a pointer.
 */
typedef struct PairasmAssembler PairasmAssembler;

/**
 * Borrowed byte slice passed across the C ABI.
 */
typedef struct PairasmBytes {
  const uint8_t *ptr;
  size_t len;
} PairasmBytes;

/**
 * Borrowed read record view passed across the C ABI.
 */
typedef struct PairasmReadView {
  struct PairasmBytes id;
  struct PairasmBytes sequence;
  struct PairasmBytes quality;
} PairasmReadView;

/**
 * Owned merged read returned across the C ABI.
 */
typedef struct PairasmMergedRead {
  uint8_t *id;
  size_t id_len;
  uint8_t *sequence;
  size_t sequence_len;
  uint8_t *quality;
  size_t quality_len;
} PairasmMergedRead;

/**
 * Allocate a default assembler handle.
 *
 * The caller owns the returned handle and must release it with [`pairasm_assembler_free`].
 *
 * # Safety
 *
 * `out` must be either null or a valid writable pointer to storage for one assembler pointer.
 */
enum PairasmStatus pairasm_assembler_new(struct PairasmAssembler **out);

/**
 * Free an assembler handle allocated by [`pairasm_assembler_new`].
 *
 * # Safety
 *
 * `assembler` must be null or a pointer previously returned by [`pairasm_assembler_new`] that has
 * not already been freed.
 */
void pairasm_assembler_free(struct PairasmAssembler *assembler);

/**
 * Process one read pair with a Rust-owned assembler.
 *
 * On [`PairasmStatus::Ok`], `out` owns a merged read and must be freed with
 * [`pairasm_merged_read_free`]. On [`PairasmStatus::NoOverlap`], `out` is empty. On error,
 * `error_out` receives a Rust-allocated NUL-terminated message when `error_out` is non-null.
 *
 * # Safety
 *
 * `assembler` must be a valid pointer returned by [`pairasm_assembler_new`]. Each non-empty input
 * byte view must point to readable memory for its declared length for the duration of this call.
 * `out` must be a valid writable pointer. `error_out` may be null; when non-null, it must be a
 * valid writable pointer to storage for one error-string pointer.
 */
enum PairasmStatus pairasm_process_pair(struct PairasmAssembler *assembler,
                                        struct PairasmReadView forward,
                                        struct PairasmReadView reverse,
                                        struct PairasmMergedRead *out,
                                        char **error_out);

/**
 * Free a merged read allocated by [`pairasm_process_pair`].
 *
 * # Safety
 *
 * `read` must be null or a valid writable pointer to a [`PairasmMergedRead`] initialized by this
 * library. Each non-null field pointer in the struct must still be owned by the struct.
 */
void pairasm_merged_read_free(struct PairasmMergedRead *read);

/**
 * Free an error string allocated by this library.
 *
 * # Safety
 *
 * `error` must be null or a pointer previously returned through an ABI `error_out` parameter that
 * has not already been freed.
 */
void pairasm_error_free(char *error);

#endif  /* LIBPAIRASSEMBLY_H */
